version: '3.5'

services:
  shippinggo_vesselms:
    restart: always
    container_name: "shippinggo_vesselms"
    build: .
    ports:
      - 50052:50051 #exposing this port on the docker network only not host
    links:
      - datastore
    depends_on: 
      - datastore
    networks:
      - shippinggo-backend-tier #network to communicate with the other services
      - vesselms-tier #internal network to communicate with the DB
    environment: 
      DB_HOST: "mongodb://datastore:27017"
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTERY: "mdns"
  
  datastore:
    image: mongo:latest
    container_name: "shippinggo_vesselms_datastore"
    environment: 
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db #ensure data persistence between restarts
    networks: 
      - vesselms-tier
    ports:
      - 27017
    command: mongod --logpath=/dev/null
networks: 
  vesselms-tier:
    name: vesselms-tier
  shippinggo-backend-tier:
    external: 
      name: shippinggo-backend-tier
