// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consignement/consignement.proto

package consignement

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Consignement struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight               int32        `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	VesselId             string       `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignement) Reset()         { *m = Consignement{} }
func (m *Consignement) String() string { return proto.CompactTextString(m) }
func (*Consignement) ProtoMessage()    {}
func (*Consignement) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bef958e18f7a808, []int{0}
}

func (m *Consignement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignement.Unmarshal(m, b)
}
func (m *Consignement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignement.Marshal(b, m, deterministic)
}
func (m *Consignement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignement.Merge(m, src)
}
func (m *Consignement) XXX_Size() int {
	return xxx_messageInfo_Consignement.Size(m)
}
func (m *Consignement) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignement.DiscardUnknown(m)
}

var xxx_messageInfo_Consignement proto.InternalMessageInfo

func (m *Consignement) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignement) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignement) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignement) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignement) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bef958e18f7a808, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bef958e18f7a808, []int{2}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Response struct {
	Created              bool            `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Consignement         *Consignement   `protobuf:"bytes,2,opt,name=consignement,proto3" json:"consignement,omitempty"`
	Consignements        []*Consignement `protobuf:"bytes,3,rep,name=consignements,proto3" json:"consignements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bef958e18f7a808, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetConsignement() *Consignement {
	if m != nil {
		return m.Consignement
	}
	return nil
}

func (m *Response) GetConsignements() []*Consignement {
	if m != nil {
		return m.Consignements
	}
	return nil
}

func init() {
	proto.RegisterType((*Consignement)(nil), "consignement.Consignement")
	proto.RegisterType((*GetRequest)(nil), "consignement.GetRequest")
	proto.RegisterType((*Container)(nil), "consignement.Container")
	proto.RegisterType((*Response)(nil), "consignement.Response")
}

func init() {
	proto.RegisterFile("proto/consignement/consignement.proto", fileDescriptor_6bef958e18f7a808)
}

var fileDescriptor_6bef958e18f7a808 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xcd, 0x4e, 0x2a, 0x31,
	0x14, 0xbe, 0xc3, 0xff, 0x9c, 0xe1, 0xde, 0x6b, 0xce, 0x02, 0x1a, 0x5c, 0x38, 0x99, 0xc4, 0x84,
	0x15, 0x26, 0xb8, 0x70, 0x67, 0x4c, 0x48, 0x24, 0xb8, 0x2c, 0x0f, 0x60, 0x70, 0xe6, 0x64, 0x68,
	0x22, 0xed, 0xd8, 0x16, 0x7c, 0x22, 0x5d, 0xfa, 0x8c, 0x86, 0x0e, 0x83, 0xd3, 0x10, 0x59, 0x7e,
	0x3f, 0xfd, 0xce, 0xd7, 0x9e, 0xc2, 0x75, 0xa1, 0x95, 0x55, 0x37, 0xa9, 0x92, 0x46, 0xe4, 0x92,
	0x36, 0x24, 0xad, 0x07, 0x26, 0x4e, 0xc7, 0x7e, 0x9d, 0x4b, 0xbe, 0x02, 0xe8, 0xcf, 0x6a, 0x04,
	0xfe, 0x83, 0x86, 0xc8, 0x58, 0x10, 0x07, 0xe3, 0x90, 0x37, 0x44, 0x86, 0x31, 0x44, 0x19, 0x99,
	0x54, 0x8b, 0xc2, 0x0a, 0x25, 0x59, 0xc3, 0x09, 0x75, 0x0a, 0x07, 0xd0, 0x79, 0x27, 0x91, 0xaf,
	0x2d, 0x6b, 0xc6, 0xc1, 0xb8, 0xcd, 0x0f, 0x08, 0xef, 0x00, 0x52, 0x25, 0xed, 0x4a, 0x48, 0xd2,
	0x86, 0xb5, 0xe2, 0xe6, 0x38, 0x9a, 0x0e, 0x27, 0x5e, 0xa3, 0x59, 0xa5, 0xf3, 0x9a, 0x15, 0x2f,
	0x21, 0xdc, 0x91, 0x31, 0xf4, 0xfa, 0x2c, 0x32, 0xd6, 0x76, 0x03, 0x7b, 0x25, 0xb1, 0xc8, 0x92,
	0x3e, 0xc0, 0x9c, 0x2c, 0xa7, 0xb7, 0x2d, 0x19, 0x9b, 0x6c, 0x20, 0x3c, 0x66, 0x9c, 0x54, 0xbf,
	0x82, 0x28, 0xdd, 0x1a, 0xab, 0x36, 0xa4, 0xf7, 0x49, 0x65, 0x75, 0xa8, 0xa8, 0x45, 0xb6, 0x6f,
	0xae, 0xb4, 0xc8, 0x85, 0x74, 0xcd, 0x43, 0x7e, 0x40, 0x38, 0x84, 0xee, 0xd6, 0x94, 0x87, 0x5a,
	0xa5, 0xb0, 0x87, 0x8b, 0x2c, 0xf9, 0x0c, 0xa0, 0xc7, 0xc9, 0x14, 0x4a, 0x1a, 0x42, 0x06, 0xdd,
	0x54, 0xd3, 0xca, 0x52, 0x39, 0xb3, 0xc7, 0x2b, 0x88, 0xf7, 0xe0, 0x3d, 0xb2, 0x9b, 0x1c, 0x4d,
	0x47, 0x27, 0x77, 0x3f, 0x02, 0xee, 0xf9, 0xf1, 0x01, 0xfe, 0xd6, 0xb1, 0x61, 0x4d, 0xf7, 0x78,
	0xe7, 0x02, 0xfc, 0x03, 0xd3, 0x8f, 0x00, 0xfe, 0x2f, 0xd7, 0xa2, 0x28, 0x84, 0xcc, 0x97, 0xa4,
	0x77, 0x22, 0x25, 0x7c, 0x02, 0x9c, 0xb9, 0x82, 0xde, 0xbe, 0xcf, 0x84, 0x8e, 0x06, 0xbe, 0x56,
	0xdd, 0x3c, 0xf9, 0x83, 0x8f, 0x70, 0x31, 0x27, 0x5b, 0x37, 0x1b, 0x64, 0xbe, 0xfb, 0x67, 0x4b,
	0xbf, 0xe7, 0xbc, 0x74, 0xdc, 0x9f, 0xbc, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x63, 0x29,
	0x14, 0xbc, 0x02, 0x00, 0x00,
}
