version: '3.5'

services:
  shippinggo_consignementms:
    restart: always
    container_name: "shippinggo_consignementms"
    build: .
    # ports:
    #   - 50051:50051 #exposing this port on the docker network only not host
    depends_on: 
      - datastore
    network_mode: host
    # networks:
    #   #- shippinggo-backend-tier #network to communicate with the other services
    #   - consignement-tier #internal network to communicate with the DB
    environment: 
      DB_HOST: "mongodb://127.0.0.1:27017"
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTERY: "mdns"
  
  datastore:
    restart: always
    # networks:
    #   - consignement-tier
    image: mongo:latest
    ports:
      - 27017:27017
# networks: 
#   # shippinggo-backend-tier:
#   #   name: shippinggo-backend-tier
#   consignement-tier:
#     name: consignement-tier
